config/routes.rb
      scope module: :employees do
        resource :cce_record, only: :show
        resource :career_path, only: :show

        resources :evaluations,
          only: [:index, :show, :new, :create]
          
        resources :qces, only: [:index, :show] do
          scope module: :qces do
            rating_types = [:instructions, :extensions,
                                :productions, :researches]

            resources *rating_types, only: :show

            # QCE Summary Sheet for Teaching Effectiveness by Evaluator Type
            resource :instruction_summary_sheet, only: :show,
              path: 'instruction-summary-sheet-by-evaluator-type'

            # QCE Summary Sheet for Research, Extension, Production by Evaluator Type
            resource :support_area_summary_sheet, only: :show,
              path: 'support-area-summary-sheet-by-evaluator-type'

            # Computation of Summary of Rating Per Semester
            resource :computation_summary_rating, only: :show,
              path: 'computation-of-summary-rating-per-semester'

            # QCE Computation of the Summary of Rating for the Whole Evaluation Period
            # (Summary Sheet for Whole Evaluation Period)
            # resource :whole_evaluation_period_summary_sheet
          end   # scope module: :qces
        end   # resources :qces

        resources :leaves, except: :show
        resources :leave_service_credits, except: [:index, :show]

        # "Educations (tab)" and resources under it 
        #   (should be namespaced instead)
        resources :educations, only: :index
          resources :academic_degrees, except: [:index, :show]
          resources :additional_degrees, except: [:index, :show]
          resources :additional_credits, except: [:index, :show]
          resources :trainings, except: [:index, :show]

        # "Work Experiences (tab)" and resources under it 
        #   (should be namespaced instead)
        resources :work_experiences, only: :index
          resources :academic_work_experiences, except: [:index, :show]
          resources :admin_work_experiences, except: [:index, :show]
          resources :professional_work_experiences,
            except: [:index, :show]
          resources :public_private_work_experiences,
            except: [:index, :show]

        # "Achievement and Honors (tabs 1 & 2)" and resources under it 
        #   (should be namespaced instead)
        resource :achievement_and_honors_1, only: :show,
          path: "discoveries-and-creative-works"

          resources :creative_works, except: [:index, :show]
          resources :discoveries, except: [:index, :show]
          resources :innovations, except: [:index, :show]
          resources :instructional_manuals, except: [:index, :show]
          resources :inventions, except: [:index, :show]
          resources :publications, except: [:index, :show]
          resources :technical_articles, except: [:index, :show]
                  
        resource :achievement_and_honors_2, only: :show,
          path: "achievement-and-honors"

          resources :academic_honors, except: [:index, :show]
          resources :awards, except: [:index, :show]
          resources :community_outreaches, except: [:index, :show]
          resources :professional_examinations, except: [:index, :show]
          resources :professional_memberships, except: [:index, :show]
          resources :scholarships, except: [:index, :show]

        # "Expert Services (tab)" and resources under it 
        #   (should be namespaced instead)
        resources :expert_services, only: :index,
          path: "expert-services"

          resources :academic_advisories, except: [:index, :show]
          resources :accreditation_services, except: [:index, :show]
          resources :assessor_services, except: [:index, :show]
          resources :professional_reviews, except: [:index, :show]
          resources :professional_services, except: [:index, :show]
          resources :consultancy_services, except: [:index, :show]
          resources :trainer_services, except: [:index, :show]
    
        # TODO: Delete all files related to these resources:
          # resources :rankings
          # resources :civil_service_eligibilities
          # resources :other_infos
          # resources :voluntary_works
      end
    end   # resources :employees

    resources :departments
    resources :leaves
    resources :leave_service_credits
    resources :holidays

    resources :career_paths
    resources :specializations
    resources :career_path_actions
    
    resources :academic_years, path: 'academic-years'
    # resources :rating_periods, path: 'rating-periods'
    resources :academic_rankings, only: :index, path: 'academic-rankings'

    resources :admins
    resources :users
    resources :students
    # resources :clients

    resource :account, only: [:edit, :update]
  end   # namespace :admin

  scope module: :user do
    root 'sessions#new'

    get 'login' => 'sessions#new'
    delete 'logout' => 'sessions#destroy'
    post 'login' => 'sessions#create', as: :authenticate_user

    resource :dashboard, only: :show

    resource :hr_profile, only: :show, path: 'my-hr-profile' do
      patch "personal_info", action: "update_personal_info"
      patch "gov_membership_info", action: "update_gov_membership_info"
      patch "addresses_info", action: "update_addresses_info"
    end

    resource :career_path, only: :show, path: 'my-career-path'

    resource :cce_record, only: :show
    scope path: "cce_record", module: :cce_record do
      resources :academic_degrees, except: [:index, :show]
      resources :additional_degrees, except: [:index, :show]
      resources :additional_credits, except: [:index, :show]
      resources :trainings, except: [:index, :show]

      resources :academic_work_experiences, except: [:index, :show]
      resources :admin_work_experiences, except: [:index, :show]
      resources :professional_work_experiences, except: [:index, :show]
      resources :public_private_work_experiences, except: [:index, :show]

      resources :creative_works, except: [:index, :show]
      resources :discoveries, except: [:index, :show]
      resources :innovations, except: [:index, :show]
      resources :instructional_manuals, except: [:index, :show]
      resources :inventions, except: [:index, :show]
      resources :publications, except: [:index, :show]
      resources :technical_articles, except: [:index, :show]

      resources :academic_honors, except: [:index, :show]
      resources :awards, except: [:index, :show]
      resources :community_outreaches, except: [:index, :show]
      resources :professional_examinations, except: [:index, :show]
      resources :professional_memberships, except: [:index, :show]
      resources :scholarships, except: [:index, :show]

      resources :academic_advisories, except: [:index, :show]
      resources :accreditation_services, except: [:index, :show]
      resources :assessor_services, except: [:index, :show]
      resources :professional_reviews, except: [:index, :show]
      resources :professional_services, except: [:index, :show]
      resources :consultancy_services, except: [:index, :show]
      resources :trainer_services, except: [:index, :show]
    end

    resource :account, only: [:edit, :update], path: 'user-account',
              as: :user_account

    resources :leaves, only: :index
    resources :rating_tasks, only: :index

    resources :qces, except: :new do
      member do
        delete 'support_area' => 'qces#destroy_support_area'
        patch 'finalize' => 'qces#finalize'
      end

      scope module: :qces do
        # Should have been an object that manages adding these different type of QCE::InstructionRating
        resource :self_instruction_rating, only: [:create, :destroy]
        # class User::QCEs::SelfInstructionRatingsController

        resource :supervisor_instruction_rating, only: [:create, :destroy]
        resource :peer_instruction_rating, only: [:create, :destroy]
        resource :student_instruction_rating, only: [:create, :destroy]

        resource :clientele_instrument, only: [:create, :destroy]
        resource :leadership_instrument, only: [:create, :destroy]
        resource :partnership_instrument, only: [:create, :destroy]
        resource :community_instrument, only: [:create, :destroy]

        rating_types = [:instructions, :extensions,
                            :productions, :researches]
        rating_actions = [:show, :edit, :update]
        custom_path_names = { edit: :evaluate }

        resources *rating_types, only: rating_actions,
                                  path_names: custom_path_names do
          member do
            patch 'randomize_save'
          end
        end

        # QCE Summary Sheet for Teaching Effectiveness by Evaluator Type
        resource :instruction_summary_sheet, only: :show,
          path: 'instruction-summary-sheet-by-evaluator-type'

        # QCE Summary Sheet for Research, Extension, Production by Evaluator Type
        resource :support_area_summary_sheet, only: :show,
          path: 'support-area-summary-sheet-by-evaluator-type'

        # Computation of Summary of Rating Per Semester
        resource :computation_summary_rating, only: :show,
          path: 'computation-of-summary-rating-per-semester'

        # QCE Computation of the Summary of Rating for the Whole Evaluation Period
        # (Summary Sheet for Whole Evaluation Period)
        # resource :whole_evaluation_period_summary_sheet

      end   # scope module: :qces
    end   # resources :qces
  end   # scope module: :user

end   # Rails.application.routes.draw do

# scope module: :evaluations do      
#     resources :instruction_ratings,
#       module: :qce,
#       only: [:edit, :update],
#       path: 'evaluate/instruction_ratings',
#       path_names: { edit:  'evaluate' },
#       as: 'evaluate_qce_instruction_rating'

app/models/department.rb
# == Schema Information
#
# Table name: departments
#
#  id         :integer          not null, primary key
#  name       :string(40)       not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_departments_on_name  (name) UNIQUE
#

class Department < ActiveRecord::Base
  has_many :employees, -> { includes(:rank).
                            order(last_name: :asc, first_name: :asc)
                          }
  has_many :students, dependent: :destroy
  
  validates :name, presence: true,
                    uniqueness: true,
                    length: { maximum: 40 }


  def self.get_field_limit_of(field_name)
    column_for_attribute(field_name.to_s.to_sym).limit
  end

end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < Admin::ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
    @departments = Department.order(name: :asc)
  end

  def show
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to admin_departments_path, notice: 'Department record was successfully created.' }
      else
        format.html { render :new }
      end
    end    
  end

  def edit
  end

  def update
    # render html: params.inspect and return true

    respond_to do |format|    
      if @department.update(department_params)
        format.html {
          redirect_to admin_departments_path,
          notice: 'Department record was successfully updated.'
        }
      else
        format.html { render :edit }
      end
    end    
  end

  def destroy
    @department.destroy
    respond_to do |format|
      format.html {
        redirect_to admin_departments_path,
        notice: 'Department record was successfully deleted.' 
      }
    end
  end


  private  

  def set_department
    @department = Department.find(params[:id])
  end

  def department_params
    params.require(:department).permit(:name)
  end

end

app/views/admin/departments/_form.html.erb
<%= form_for [:admin, @department] do |f| %>
  <%= error_messages_for(@department) %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', autofocus: true, maxlength: Department.get_field_limit_of(:name) %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
      </div>      
    </div>
  </div>
<% end %>

app/views/admin/departments/edit.html.erb
<h2 class="page-header">Edit Department</h2>
<%= render 'form' %>
<%= link_to '< Back to Departments', admin_departments_path, class: 'btn btn-link' %> |&nbsp;
<%= link_to 'Show', admin_department_path(@department), class: 'btn btn-link' %>

app/views/admin/departments/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-header">
      <span>Departments</span>
      <span class="pull-right">
        <%= link_to new_admin_department_path, class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-plus"></span> New
        <% end %>
      </span>
    </h2>
  </div>  <!-- .col-md-12 -->
</div> <!-- .row -->
<table class="table table-bordered table-striped table-master content">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @departments.each_with_index do |department, index| %>
      <tr>
        <td><%= index += 1 %></td>
        <td><%= link_to department.name, admin_department_path(department), title: 'View', data: { toggle: 'tooltip' } %></td>
        <td>
          <%= link_to edit_admin_department_path(department), title: 'Edit', data: { toggle: 'tooltip'} do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to admin_department_path(department), method: :delete,
                title: 'Delete',
                data: { toggle: 'tooltip', confirm: 'Do you really want to delete this record?' } do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/departments/new.html.erb
<h2 class="page-header">New Department</h2>
<%= render 'form' %>
<%= link_to '< Back to Departments', admin_departments_path, class: 'btn btn-link' %>

app/views/admin/departments/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h2 class="page-header"><%= @department.name %></h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h4 class="page-header">Faculty members under this department:</h4>
    <table class="table table-bordered table-striped table-master content">
      <thead>
        <tr>
          <th>#</th>
          <th>Faculty</th>
          <th>Rank</th>
          <th colspan="2">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @department.employees.each_with_index do |emp, index| %>
          <tr>
            <td><%= index += 1 %></td>
            <td><%= link_to emp.full_name, admin_employee_path(emp), title: 'View', data: { toggle: 'tooltip' } %></td>
            <td><%= emp.rank.full_name %></td>
            <td>
              <%= link_to edit_admin_employee_path(emp), title: 'Edit', data: { toggle: 'tooltip'} do %>
                <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
              <%= link_to admin_employee_path(emp), method: :delete,
                    title: 'Delete',
                    data: { toggle: 'tooltip', confirm: 'Do you really want to delete this record?' } do %>
                <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>  
  </div>
</div>
<div class="links">
  <%= link_to '< Back to Departments', admin_departments_path, class: 'btn btn-link' %> |&nbsp;
  <%= link_to 'Edit', edit_admin_department_path(@department), class: 'btn btn-link' %>
</div>