config/routes.rb
      scope module: :employees do
        resource :cce_record, only: :show
        resource :career_path, only: :show

        resources :evaluations,
          only: [:index, :show, :new, :create]
          
        resources :qces, only: [:index, :show] do
          scope module: :qces do
            rating_types = [:instructions, :extensions,
                                :productions, :researches]

            resources *rating_types, only: :show

            # QCE Summary Sheet for Teaching Effectiveness by Evaluator Type
            resource :instruction_summary_sheet, only: :show,
              path: 'instruction-summary-sheet-by-evaluator-type'

            # QCE Summary Sheet for Research, Extension, Production by Evaluator Type
            resource :support_area_summary_sheet, only: :show,
              path: 'support-area-summary-sheet-by-evaluator-type'

            # Computation of Summary of Rating Per Semester
            resource :computation_summary_rating, only: :show,
              path: 'computation-of-summary-rating-per-semester'

            # QCE Computation of the Summary of Rating for the Whole Evaluation Period
            # (Summary Sheet for Whole Evaluation Period)
            # resource :whole_evaluation_period_summary_sheet
          end   # scope module: :qces
        end   # resources :qces

        resources :leaves, except: :show
        resources :leave_service_credits, except: [:index, :show]

        # "Educations (tab)" and resources under it 
        #   (should be namespaced instead)
        resources :educations, only: :index
          resources :academic_degrees, except: [:index, :show]
          resources :additional_degrees, except: [:index, :show]
          resources :additional_credits, except: [:index, :show]
          resources :trainings, except: [:index, :show]

        # "Work Experiences (tab)" and resources under it 
        #   (should be namespaced instead)
        resources :work_experiences, only: :index
          resources :academic_work_experiences, except: [:index, :show]
          resources :admin_work_experiences, except: [:index, :show]
          resources :professional_work_experiences,
            except: [:index, :show]
          resources :public_private_work_experiences,
            except: [:index, :show]

        # "Achievement and Honors (tabs 1 & 2)" and resources under it 
        #   (should be namespaced instead)
        resource :achievement_and_honors_1, only: :show,
          path: "discoveries-and-creative-works"

          resources :creative_works, except: [:index, :show]
          resources :discoveries, except: [:index, :show]
          resources :innovations, except: [:index, :show]
          resources :instructional_manuals, except: [:index, :show]
          resources :inventions, except: [:index, :show]
          resources :publications, except: [:index, :show]
          resources :technical_articles, except: [:index, :show]
                  
        resource :achievement_and_honors_2, only: :show,
          path: "achievement-and-honors"

          resources :academic_honors, except: [:index, :show]
          resources :awards, except: [:index, :show]
          resources :community_outreaches, except: [:index, :show]
          resources :professional_examinations, except: [:index, :show]
          resources :professional_memberships, except: [:index, :show]
          resources :scholarships, except: [:index, :show]

        # "Expert Services (tab)" and resources under it 
        #   (should be namespaced instead)
        resources :expert_services, only: :index,
          path: "expert-services"

          resources :academic_advisories, except: [:index, :show]
          resources :accreditation_services, except: [:index, :show]
          resources :assessor_services, except: [:index, :show]
          resources :professional_reviews, except: [:index, :show]
          resources :professional_services, except: [:index, :show]
          resources :consultancy_services, except: [:index, :show]
          resources :trainer_services, except: [:index, :show]
    
        # TODO: Delete all files related to these resources:
          # resources :rankings
          # resources :civil_service_eligibilities
          # resources :other_infos
          # resources :voluntary_works
      end
    end   # resources :employees

    resources :departments
    resources :leaves
    resources :leave_service_credits
    resources :holidays

    resources :career_paths
    resources :specializations
    resources :career_path_actions
    
    resources :academic_years, path: 'academic-years'
    # resources :rating_periods, path: 'rating-periods'
    resources :academic_rankings, only: :index, path: 'academic-rankings'

    resources :admins
    resources :users
    resources :students
    # resources :clients

    resource :account, only: [:edit, :update]
  end   # namespace :admin

  scope module: :user do
    root 'sessions#new'

    get 'login' => 'sessions#new'
    delete 'logout' => 'sessions#destroy'
    post 'login' => 'sessions#create', as: :authenticate_user

    resource :dashboard, only: :show

    resource :hr_profile, only: :show, path: 'my-hr-profile' do
      patch "personal_info", action: "update_personal_info"
      patch "gov_membership_info", action: "update_gov_membership_info"
      patch "addresses_info", action: "update_addresses_info"
    end

    resource :career_path, only: :show, path: 'my-career-path'

    resource :cce_record, only: :show
    scope path: "cce_record", module: :cce_record do
      resources :academic_degrees, except: [:index, :show]
      resources :additional_degrees, except: [:index, :show]
      resources :additional_credits, except: [:index, :show]
      resources :trainings, except: [:index, :show]

      resources :academic_work_experiences, except: [:index, :show]
      resources :admin_work_experiences, except: [:index, :show]
      resources :professional_work_experiences, except: [:index, :show]
      resources :public_private_work_experiences, except: [:index, :show]

      resources :creative_works, except: [:index, :show]
      resources :discoveries, except: [:index, :show]
      resources :innovations, except: [:index, :show]
      resources :instructional_manuals, except: [:index, :show]
      resources :inventions, except: [:index, :show]
      resources :publications, except: [:index, :show]
      resources :technical_articles, except: [:index, :show]

      resources :academic_honors, except: [:index, :show]
      resources :awards, except: [:index, :show]
      resources :community_outreaches, except: [:index, :show]
      resources :professional_examinations, except: [:index, :show]
      resources :professional_memberships, except: [:index, :show]
      resources :scholarships, except: [:index, :show]

      resources :academic_advisories, except: [:index, :show]
      resources :accreditation_services, except: [:index, :show]
      resources :assessor_services, except: [:index, :show]
      resources :professional_reviews, except: [:index, :show]
      resources :professional_services, except: [:index, :show]
      resources :consultancy_services, except: [:index, :show]
      resources :trainer_services, except: [:index, :show]
    end

    resource :account, only: [:edit, :update], path: 'user-account',
              as: :user_account

    resources :leaves, only: :index
    resources :rating_tasks, only: :index

    resources :qces, except: :new do
      member do
        delete 'support_area' => 'qces#destroy_support_area'
        patch 'finalize' => 'qces#finalize'
      end

      scope module: :qces do
        # Should have been an object that manages adding these different type of QCE::InstructionRating
        resource :self_instruction_rating, only: [:create, :destroy]
        # class User::QCEs::SelfInstructionRatingsController

        resource :supervisor_instruction_rating, only: [:create, :destroy]
        resource :peer_instruction_rating, only: [:create, :destroy]
        resource :student_instruction_rating, only: [:create, :destroy]

        resource :clientele_instrument, only: [:create, :destroy]
        resource :leadership_instrument, only: [:create, :destroy]
        resource :partnership_instrument, only: [:create, :destroy]
        resource :community_instrument, only: [:create, :destroy]

        rating_types = [:instructions, :extensions,
                            :productions, :researches]
        rating_actions = [:show, :edit, :update]
        custom_path_names = { edit: :evaluate }

        resources *rating_types, only: rating_actions,
                                  path_names: custom_path_names do
          member do
            patch 'randomize_save'
          end
        end

        # QCE Summary Sheet for Teaching Effectiveness by Evaluator Type
        resource :instruction_summary_sheet, only: :show,
          path: 'instruction-summary-sheet-by-evaluator-type'

        # QCE Summary Sheet for Research, Extension, Production by Evaluator Type
        resource :support_area_summary_sheet, only: :show,
          path: 'support-area-summary-sheet-by-evaluator-type'

        # Computation of Summary of Rating Per Semester
        resource :computation_summary_rating, only: :show,
          path: 'computation-of-summary-rating-per-semester'

        # QCE Computation of the Summary of Rating for the Whole Evaluation Period
        # (Summary Sheet for Whole Evaluation Period)
        # resource :whole_evaluation_period_summary_sheet

      end   # scope module: :qces
    end   # resources :qces
  end   # scope module: :user

end   # Rails.application.routes.draw do

# scope module: :evaluations do      
#     resources :instruction_ratings,
#       module: :qce,
#       only: [:edit, :update],
#       path: 'evaluate/instruction_ratings',
#       path_names: { edit:  'evaluate' },
#       as: 'evaluate_qce_instruction_rating'

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:admin, @user], notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end      
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to [:admin, @user], notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'User was successfully deleted.'
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
  
end

app/controllers/user/account_controller.rb
class User::AccountController < User::ApplicationController

  def edit
  end

  def update
    user = @current_user.authenticate(params[:current_password])
    if user
      # User knows his current password, so allow him to update his account with the new data.
      if @current_user.update(username: params[:username], 
                            password: params[:new_password])
        logout_current_user
        redirect_to login_path, notice: 'User account updated successfully. Please login again.'
      else
        # Display model's validation errors
        render :edit
      end
    else
      flash.now.alert = "Current password is invalid."
      render :edit
    end
       
    # @current_user.username = params[:username]
    # @current_user.password = params[:new]
    #new_password = params[:user][:password]
    # if @user.update_account(user_params, new_password)
    # if @user.change_password(old_password, new_password)
  end
  

  private

  # def set_user
  #   # @current_user ||= User.find(session[:user_id]) if session[:user_id]
  #   @user = current_user
  # end

  def user_params
    params.require(:user).permit(:username, :password, :password_digest, 
      :new_password, :current_password)
  end

end

app/controllers/user/application_controller.rb
class User::ApplicationController < ActionController::Base
  AUTHORIZATION_MSG = 'In order to continue, you are required to login first.'

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authorize_user
  helper_method :current_user, :user_signed_in?


  private

  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue
      session[:user_id] = nil
      #redirect_to(login_path) and return true
    end
  end

  def authorize_user
    redirect_to login_path, alert: AUTHORIZATION_MSG if current_user.nil?
  end

  def user_signed_in?
    !!current_user
  end

  def logout_current_user
    session[:user_id] = nil
    # reset_session
  end

end

app/controllers/user/career_paths_controller.rb
class User::CareerPathsController < User::ApplicationController

  def show
    @specialization = current_user.account.specialization
    if @specialization.present? 
      @actions = @specialization.career_path_actions.
                  order(category: :asc, start_at: :desc, end_at: :desc)
    else
      render 'no_career_path' and return true
    end
  end
  
end

app/controllers/user/cce_record/academic_advisories_controller.rb
class User::CCERecord::AcademicAdvisoriesController < User::ApplicationController

  before_action :set_employee
  before_action :set_advisory, only: [:edit, :update, :destroy]


  def new
    @advisory = employee.academic_advisories.new
  end

  def create
    @advisory = employee.academic_advisories.new(advisory_params)
    if @advisory.save
      redirect_to cce_record_path,
        notice: "Academic advisory record was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @advisory.update(advisory_params)
      redirect_to cce_record_path,
        notice: "Academic advisory record was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @advisory.destroy
    redirect_to cce_record_path,
      notice: "Academic advisory record was successfully deleted."
  end


  private


  def employee
    @employee = current_user.account
  end

  alias_method :set_employee, :employee
  

  def set_advisory
    @advisory = employee.academic_advisories.find(params[:id])
  end

  def advisory_params
    params.require(:academic_advisory).
      permit(:title, :nature, :start_at, :end_at)
  end

end

app/controllers/user/cce_record/academic_degrees_controller.rb
class User::CCERecord::AcademicDegreesController < User::ApplicationController

  before_action :set_employee
  before_action :set_degree, only: [:edit, :update, :destroy]


  def new
    @degree = employee.academic_degrees.new
  end

  def create
    @degree = employee.academic_degrees.new(academic_degree_params)
    if @degree.save
      redirect_to cce_record_path,
        notice: "Academic degree record was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @degree.update(academic_degree_params)
      redirect_to cce_record_path,
        notice: "Academic degree record was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @degree.destroy
    redirect_to cce_record_path,
      notice: "Academic degree record was successfully deleted."
  end


  private


  def employee
    @employee = current_user.account
  end

  alias_method :set_employee, :employee


  def set_degree
    @degree = employee.academic_degrees.find(params[:id])
  end

  def academic_degree_params
    params.require(:academic_degree).permit(:institution, :degree,
                                            :degree_type, :start_at,
                                            :end_at, :graduated_at)
  end

end

app/controllers/user/cce_record/academic_honors_controller.rb
class User::CCERecord::AcademicHonorsController < User::ApplicationController

  before_action :set_employee
  before_action :set_academic_honor, only: [:edit, :update, :destroy]


  def new
    @academic_honor = employee.academic_honors.new
  end

  def create
    @academic_honor = employee.academic_honors.new(academic_honor_params)
    if @academic_honor.save
      redirect_to cce_record_path,
        notice: "Academic honor record was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @academic_honor.update(academic_honor_params)
      redirect_to cce_record_path,
        notice: "Academic honor record was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @academic_honor.destroy
    redirect_to cce_record_path,
      notice: "Academic honor record was successfully deleted."
  end


  private


  def employee
    @employee = current_user.account
  end

  alias_method :set_employee, :employee


  def set_academic_honor
    @academic_honor = employee.academic_honors.find(params[:id])
  end

  def academic_honor_params
    params.require(:academic_honor).permit(:award, :degree_type,
                                          :honor_type, :school,
                                            :date_awarded)
  end

end

app/views/user/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "CAPSU HR", dashboard_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "My HR Profile", hr_profile_path %></li>
        <li><%= link_to "Career Path", career_path_path %></li>
        <li><%= link_to "Leaves", leaves_path %></li>
        <li><%= link_to "CCE", cce_record_path %></li>
        <li><%= link_to "QCE", qces_path %></li>
        <li><%= link_to "Rating Tasks", rating_tasks_path %></li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <!-- Account dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Welcome, #{current_user.username}" %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_account_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete  %></li>
            </ul>
          </li>
          <!-- end of Account dropdown -->
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/user/_student_client_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'CAPSU HR', dashboard_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Rating Tasks', rating_tasks_path %></li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <!-- Account dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Welcome, #{current_user.username}" %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Account', edit_user_account_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log out', logout_path, method: :delete  %></li>              
            </ul>
          </li>
          <!-- end of Account dropdown -->
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/user/_student_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'CAPSU HR', dashboard_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Rating Tasks', rating_tasks_path %></li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <!-- Account dropdown -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Welcome, #{current_user.username}" %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Account', edit_user_account_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log out', logout_path, method: :delete  %></li>              
            </ul>
          </li>
          <!-- end of Account dropdown -->
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>