config/routes.rb
Rails.application.routes.draw do

  post 'admin/login' => 'admin/sessions#create', as: :authenticate_admin

  namespace :admin do    
    # root to: redirect('admin/dashboard')
    root 'sessions#new'

    get 'login' => 'sessions#new'
    delete 'logout' => 'sessions#destroy'

    get 'faculty/search' => "employee_searches#index"
    get 'faculty/query' => "employee_queries#index"
    get 'faculty-career-pathing' => "employee_career_pathings#index"

    # get "faculty-evaluation/search" =>
    #   "search_employee_evaluations#index"
    resources :search_employee_evaluations,
      path: "faculty-evaluation/search", only: :index

    #get 'leaves/view' => "leave_viewings#index"
    #get 'leaves/search' => "leave_searches#index"
    #get 'leave_service_credits/search' => "leave_service_credits#index"

    resource :dashboard, only: :show
    resources :test_rankings, only: [:index, :show]

    resources :nbcs do
      member do
        patch 'close'
        patch 'open'
        
        get 'associate-academic-years'
        patch 'update-academic-years'
        patch 'remove_academic_years_association'
      end
    end

    resources :employees do
      scope module: :employees do
        resource :cce_record, only: :show
        resource :career_path, only: :show

        resources :evaluations,
          only: [:index, :show, :new, :create]
          
        resources :qces, only: [:index, :show] do
          scope module: :qces do
            rating_types = [:instructions, :extensions,
                                :productions, :researches]

            resources *rating_types, only: :show

            # QCE Summary Sheet for Teaching Effectiveness by Evaluator Type
            resource :instruction_summary_sheet, only: :show,
              path: 'instruction-summary-sheet-by-evaluator-type'

            # QCE Summary Sheet for Research, Extension, Production by Evaluator Type
            resource :support_area_summary_sheet, only: :show,
              path: 'support-area-summary-sheet-by-evaluator-type'

            # Computation of Summary of Rating Per Semester
            resource :computation_summary_rating, only: :show,
              path: 'computation-of-summary-rating-per-semester'

            # QCE Computation of the Summary of Rating for the Whole Evaluation Period
            # (Summary Sheet for Whole Evaluation Period)
            # resource :whole_evaluation_period_summary_sheet
          end   # scope module: :qces
        end   # resources :qces

        resources :leaves, except: :show
        resources :leave_service_credits, except: [:index, :show]

        # "Educations (tab)" and resources under it 
        #   (should be namespaced instead)
        resources :educations, only: :index
          resources :academic_degrees, except: [:index, :show]
          resources :additional_degrees, except: [:index, :show]
          resources :additional_credits, except: [:index, :show]
          resources :trainings, except: [:index, :show]

        # "Work Experiences (tab)" and resources under it 
        #   (should be namespaced instead)
        resources :work_experiences, only: :index
          resources :academic_work_experiences, except: [:index, :show]
          resources :admin_work_experiences, except: [:index, :show]
          resources :professional_work_experiences,
            except: [:index, :show]
          resources :public_private_work_experiences,
            except: [:index, :show]

        # "Achievement and Honors (tabs 1 & 2)" and resources under it 
        #   (should be namespaced instead)
        resource :achievement_and_honors_1, only: :show,
          path: "discoveries-and-creative-works"

          resources :creative_works, except: [:index, :show]
          resources :discoveries, except: [:index, :show]
          resources :innovations, except: [:index, :show]
          resources :instructional_manuals, except: [:index, :show]
          resources :inventions, except: [:index, :show]
          resources :publications, except: [:index, :show]
          resources :technical_articles, except: [:index, :show]
                  
        resource :achievement_and_honors_2, only: :show,
          path: "achievement-and-honors"

          resources :academic_honors, except: [:index, :show]
          resources :awards, except: [:index, :show]
          resources :community_outreaches, except: [:index, :show]
          resources :professional_examinations, except: [:index, :show]
          resources :professional_memberships, except: [:index, :show]
          resources :scholarships, except: [:index, :show]

        # "Expert Services (tab)" and resources under it 
        #   (should be namespaced instead)
        resources :expert_services, only: :index,
          path: "expert-services"

          resources :academic_advisories, except: [:index, :show]
          resources :accreditation_services, except: [:index, :show]
          resources :assessor_services, except: [:index, :show]
          resources :professional_reviews, except: [:index, :show]
          resources :professional_services, except: [:index, :show]
          resources :consultancy_services, except: [:index, :show]
          resources :trainer_services, except: [:index, :show]
    
        # TODO: Delete all files related to these resources:
          # resources :rankings
          # resources :civil_service_eligibilities
          # resources :other_infos
          # resources :voluntary_works
      end
    end   # resources :employees

    resources :departments
    resources :leaves
    resources :leave_service_credits
    resources :holidays

    resources :career_paths
    resources :specializations
    resources :career_path_actions
    
    resources :academic_years, path: 'academic-years'
    # resources :rating_periods, path: 'rating-periods'
    resources :academic_rankings, only: :index, path: 'academic-rankings'

    resources :admins
    resources :users
    resources :students
    # resources :clients

    resource :account, only: [:edit, :update]
  end   # namespace :admin

  scope module: :user do
    root 'sessions#new'

    get 'login' => 'sessions#new'
    delete 'logout' => 'sessions#destroy'
    post 'login' => 'sessions#create', as: :authenticate_user

    resource :dashboard, only: :show

    resource :hr_profile, only: :show, path: 'my-hr-profile' do
      patch "personal_info", action: "update_personal_info"
      patch "gov_membership_info", action: "update_gov_membership_info"
      patch "addresses_info", action: "update_addresses_info"
    end

    resource :career_path, only: :show, path: 'my-career-path'

    resource :cce_record, only: :show
    scope path: "cce_record", module: :cce_record do
      resources :academic_degrees, except: [:index, :show]
      resources :additional_degrees, except: [:index, :show]
      resources :additional_credits, except: [:index, :show]
      resources :trainings, except: [:index, :show]

      resources :academic_work_experiences, except: [:index, :show]
      resources :admin_work_experiences, except: [:index, :show]
      resources :professional_work_experiences, except: [:index, :show]
      resources :public_private_work_experiences, except: [:index, :show]

      resources :creative_works, except: [:index, :show]
      resources :discoveries, except: [:index, :show]
      resources :innovations, except: [:index, :show]
      resources :instructional_manuals, except: [:index, :show]
      resources :inventions, except: [:index, :show]
      resources :publications, except: [:index, :show]
      resources :technical_articles, except: [:index, :show]

      resources :academic_honors, except: [:index, :show]
      resources :awards, except: [:index, :show]
      resources :community_outreaches, except: [:index, :show]
      resources :professional_examinations, except: [:index, :show]
      resources :professional_memberships, except: [:index, :show]
      resources :scholarships, except: [:index, :show]

      resources :academic_advisories, except: [:index, :show]
      resources :accreditation_services, except: [:index, :show]
      resources :assessor_services, except: [:index, :show]
      resources :professional_reviews, except: [:index, :show]
      resources :professional_services, except: [:index, :show]
      resources :consultancy_services, except: [:index, :show]
      resources :trainer_services, except: [:index, :show]
    end

    resource :account, only: [:edit, :update], path: 'user-account',
              as: :user_account

    resources :leaves, only: :index
    resources :rating_tasks, only: :index

    resources :qces, except: :new do
      member do
        delete 'support_area' => 'qces#destroy_support_area'
        patch 'finalize' => 'qces#finalize'
      end

      scope module: :qces do
        # Should have been an object that manages adding these different type of QCE::InstructionRating
        resource :self_instruction_rating, only: [:create, :destroy]
        # class User::QCEs::SelfInstructionRatingsController

        resource :supervisor_instruction_rating, only: [:create, :destroy]
        resource :peer_instruction_rating, only: [:create, :destroy]
        resource :student_instruction_rating, only: [:create, :destroy]

        resource :clientele_instrument, only: [:create, :destroy]
        resource :leadership_instrument, only: [:create, :destroy]
        resource :partnership_instrument, only: [:create, :destroy]
        resource :community_instrument, only: [:create, :destroy]

        rating_types = [:instructions, :extensions,
                            :productions, :researches]
        rating_actions = [:show, :edit, :update]
        custom_path_names = { edit: :evaluate }

        resources *rating_types, only: rating_actions,
                                  path_names: custom_path_names do
          member do
            patch 'randomize_save'
          end
        end

app/models/leave_service_credit.rb
# == Schema Information
#
# Table name: leave_service_credits
#
#  id               :integer          not null, primary key
#  employee_id      :integer          not null
#  description      :string
#  valid_at         :date             not null
#  expire_at        :date             not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  academic_year_id :integer
#  no_of_days       :integer
#
# Indexes
#
#  index_leave_service_credits_on_academic_year_id  (academic_year_id)
#  index_leave_service_credits_on_employee_id       (employee_id)
#

class LeaveServiceCredit < ActiveRecord::Base
  belongs_to :employee
  belongs_to :academic_year

  validates :employee_id, :academic_year_id, :valid_at, presence: true
  
  validates :valid_at, presence: :true
  # validates :employee, :academic_year, presence: true 
  validates :no_of_days, presence: true # numericality also
  validate :ensure_within_academic_year

  before_save :set_expire_at_date
  

  private

  def ensure_within_academic_year
    unless (academic_year.start_at..academic_year.end_at).include?(valid_at.to_date)
      errors[:base] << "Ensure that the Valid At date must be within the date range of the selected academic year period."
    end
  end

  # def correct_date_range
  #   unless end_at > start_at
  #     errors[:base] << "Invalid date range.\n'End at' date value must be greater than 'Start at' date value."
  #   end
  # end

  def set_expire_at_date
    self[:expire_at] = valid_at + 1.year
  end

end

app/controllers/admin/employees/leave_service_credits_controller.rb
class Admin::Employees::LeaveServiceCreditsController < Admin::ApplicationController

  before_action :set_employee
  before_action :set_leave_service_credit,
                only: [:edit, :update, :destroy]

  layout "employee_profile"


  def new
    @credit = @employee.leave_service_credits.new
  end

  def create
    # render html: params.inspect and return true
    @credit = @employee.leave_service_credits.new(credit_params)
    if @credit.save
      redirect_to admin_employee_leaves_path(@employee),
        notice: "Leave service credit was successfuly created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @credit.update(credit_params)
      redirect_to admin_employee_leaves_path(@employee),
        notice: "Leave service credit record was successfully updated."
    else
      render :edit
    end    
  end

  def destroy
    @credit.destroy
    redirect_to admin_employee_leaves_path(@employee),
      notice: "Leave service credit record was successfully deleted."
  end


  private

  def credit_params
    params.require(:leave_service_credit).
      permit(:academic_year_id, :no_of_days, :valid_at,
              :expire_at, :description)
  end

  def set_employee
    @employee = Employee.find(params[:employee_id])
  end

  def set_leave_service_credit
    @credit = @employee.leave_service_credits.find(params[:id])
  end
  
end

app/controllers/admin/leave_service_credits_controller.rb
class Admin::LeaveServiceCreditsController < Admin::ApplicationController

  before_action :set_leave_service_credit, only: [:show, :edit, :update, :destroy]


  def index

    if params[:search]
      criteria = ""  
      
      if params[:search][:academic_year_id].present?
        criteria << "(academic_year_id = #{params[:search][:academic_year_id]})"
      end

      if params[:search][:employee_id].present?
        if criteria.present?
          criteria << " AND (employee_id = #{params[:search][:employee_id]})"
        else
          criteria = "(employee_id = #{params[:search][:employee_id]})"
        end
      end
      
      # render html: params and return true

      if criteria.present?
         @leave_service_credits = LeaveServiceCredit.includes(:employee, :academic_year).where(criteria).order(valid_at: :desc)
      else
        @leave_service_credits = LeaveServiceCredit.includes(:employee, :academic_year).order(valid_at: :desc)
      end
    else
      @leave_service_credits = LeaveServiceCredit.includes(:employee, :academic_year).order(valid_at: :desc)
    end   # params[:search]

  end   # index

  def show
  end

  def new
    @leave_service_credit = LeaveServiceCredit.new
  end

  def create
    @leave_service_credit = LeaveServiceCredit.new(leave_service_credit_params)
  
    respond_to do |format|
      if @leave_service_credit.save
        format.html { redirect_to admin_leave_service_credits_path,
          notice: 'Leave service credit was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @leave_service_credit.update(leave_service_credit_params)
        format.html { redirect_to admin_leave_service_credits_path, 
          notice: 'Leave service credit was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @leave_service_credit.destroy
    respond_to do |format|
      format.html { redirect_to admin_leave_service_credits_path, 
        notice: 'Leave service credit was successfully deleted.' }
    end
  end


  private

  def set_leave_service_credit
    @leave_service_credit = LeaveServiceCredit.find(params[:id])
  end  

  def leave_service_credit_params
    params.require(:leave_service_credit).permit(:employee_id, :academic_year_id, :no_of_days, :description, :valid_at)
  end
  
end

app/views/admin/leave_service_credits/_form.html.erb
<%= form_for [:admin, @leave_service_credit] do |f| %>
  <%= error_messages_for(@leave_service_credit) %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :employee_id, 'Faculty' %>
        <%= f.collection_select :employee_id, Employee.all,
              :id, :full_name, { include_blank: '-- Select Faculty --' },
              class: 'form-control', autofocus: true, required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :academic_year_id, "Academic Year" %>
        <%= f.collection_select :academic_year_id,
              AcademicYear.display_all, :id, :coverage_with_details,
              { include_blank: ' -- Select Academic Year --' },
              class: 'form-control', required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :no_of_days, '# of days' %>
        <%= f.number_field :no_of_days, class: 'form-control',
              required: true %>
      </div>
    </div>
  </div>  
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :valid_at %>
        <%= f.date_field :valid_at, class: 'form-control',
              required: true %>
        <span><em>Service credit expires after 1 year its validity</em></span>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :expire_at, 'Expires at' %>
        <%= f.date_field :expire_at, class: 'form-control', disabled: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>
    </div>
  </div>  
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.submit class: 'btn btn-primary' %>
      </div>      
    </div>
  </div>
<% end %>

app/views/admin/leave_service_credits/_search_box.html.erb
<%# if params[:employee].nil? %>
  <%# value = nil %>
<%# else %>
  <%# value = params[:employee][:id] %>
<%# end %>
<%#= collection_select nil, :employee_id, Employee.order(:last_name), :id, :full_name_in_reverse, { include_blank: '-- Select Faculty --', selected: employee_id }, { class: 'form-control' } %>
<%
  if controller_name == 'leaves'
    form_submit_path = admin_leaves_path
    #clear_results_path = admin_leaves_path
  elsif controller_name == 'leave_service_credits'
    form_submit_path = admin_leave_service_credits_path
  end
%>
<div id="leave-search-box" class="row">
  <div class="col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">Search</h4>
    </div>
    <div class="panel-body">
      <%= form_tag form_submit_path, method: :get do %>
        <div class="col-md-12">
          <div class="col-md-4">
            <div class="form-group">
              <%= label_tag :academic_year_id, 'Academic Year' %>
              <%= collection_select :academic_year, :id, AcademicYear.display_all, :id, :coverage_with_details, { include_blank: '-- Select Academic Year --', selected: "e" }, { class: 'form-control', name: 'search[academic_year_id]' } %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= label_tag :employee_id, 'Faculty' %>
              <%= collection_select :employee, :id, Employee.all, :id, :full_name, { include_blank: '-- Select Faculty --', selected: "e" }, { class: 'form-control', name: 'search[employee_id]' } %>
            </div>
          </div>
          <div class="col-md-3 view-button">
            <div class="form-group">
              <%= button_tag(name: 'search[button]', type: 'submit', class: 'btn btn-default') do %>
                <%= content_tag(:strong, 'Search') %>
              <% end %>
              <%= link_to 'Clear results', form_submit_path, class: 'btn btn-default' %>               
            </div>
          </div>
        </div>  <!-- div.col-md-12 -->

        <% if false %>
          <div class="col-md-12">
            <div class="col-md-4">
              <div class="form-group">
                <%= label_tag :group_by_employees do %>
                  <%= check_box_tag :group_by_employees %> Group search results
                <% end %>
              </div>
            </div>  
          </div>
        <% end %>
      <% end %>
    </div>  <!-- div.panel-body -->
  </div>  <!-- div.panel.panel-default -->
</div>
</div>  <!-- div#leave-search-box -->

app/views/admin/leave_service_credits/edit.html.erb
<h2 class="page-header">Edit Leave Service Credit</h2>
<%= render 'form' %>
<!-- <%#= link_to 'Show', admin_leave_service_credit_path(@leave_service_credit), class: 'btn btn-link' %> | -->
<%= link_to '< Back to Leave Service Credits', admin_leave_service_credits_path , class: 'btn btn-link' %>

app/views/admin/leave_service_credits/index.html.erb
<style>
  div.panel-body {
    padding: 15px 7px 7px 7px;
  }

  form div.col-md-3 {
    // border: 1px green solid;
    padding: 0px 7px;
  }

  form > div.col-md-12 {
    // border: 1px red solid;
    padding: 0px 7px;
  }
    
  div.panel-heading {
    padding-top: 7px;
    padding-bottom: 7px;
  }
</style>
<div class="row">
  <div class="col-md-12">
    <h2 class="page-header">
      <span>Leave Service Credits<span>
      <span class="pull-right">
        <%= link_to new_admin_leave_service_credit_path, class: 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-plus"></span> New
        <% end %>
      </span>
    </h2>
  </div>  <!-- .col-md-12 -->
</div>  <!-- .row -->
<%= render 'search_box' %>
<table class="table table-bordered table-striped table-master content">
  <thead>
    <tr>
      <th>#</th>
      <th>Faculty</th>
      <th>Academic Year</th>
      <th># of days</th>
      <th>Valid At</th>
      <th>Expires At</th>
      <th>Description</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @leave_service_credits.each_with_index do |credit, index| %>
      <tr>
        <td><%= index += 1 %></td>
        <td><%= link_to credit.employee.full_name,
                  admin_employee_leaves_path(credit.employee),
                  title: "View Employee Leave data",
                  data: { toggle: "tooltip" } %></td>
        <td><%= credit.academic_year.coverage_with_details %></td>
        <td><%= credit.no_of_days %></td>
        <td><%= date_format_readable(credit.valid_at) %></td>
        <td><%= date_format_readable(credit.expire_at) %></td>
        <td><%= credit.description %></td>
        <td>
          <%= link_to edit_admin_leave_service_credit_path(credit), title: 'Edit', data: { toggle: 'tooltip' } do %>
            <span class="glyphicon glyphicon-pencil"></span>
          <% end %>
          <%= link_to admin_leave_service_credit_path(credit), title: 'Delete', method: :delete, data: { toggle: 'tooltip', confirm: 'Do you really want to delete this record?' } do %>
            <span class="glyphicon glyphicon-remove"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/leave_service_credits/new.html.erb
<h2 class="page-header">New Leave Service Credit</h2>
<%= render 'form' %>
<%= link_to '< Back to Leave Service Credits', admin_leave_service_credits_path , class: 'btn btn-link' %>

app/views/admin/leave_service_credits/show.html.erb
<h1>admin/leave_service_credits#show</h1>